Feature/cax 1 prs@134 prs terraform helm
catenax/tractusx pull request #18
Opened 2021-09-17 07:54 UTC by ouphi

2021-09-17 10:32 UTC, algattik requested changes

2021-09-17 10:32 UTC, algattik commented on coreservices/partsrelationshipservice/helm/prs/templates/deployment.yaml
> +            - containerPort: 4004
rm?

2021-09-17 10:32 UTC, algattik commented on coreservices/partsrelationshipservice/terraform/variables.tf
> +  default = "prsdev.d5a2b853cc864506ac03.germanywestcentral.aksapp.io"
please run `terraform fmt -recursive`

2021-09-17 10:32 UTC, algattik commented on coreservices/partsrelationshipservice/terraform/variables.tf
> +  description = "PRS image tag that will be deployed."
no default value?

2021-09-17 10:32 UTC, algattik commented on infrastructure/terraform/versions.tf
> +  required_version = "~> 1.0"
no need to update shared TF code

2021-09-17 11:51 UTC, chrislomonico commented on .github/workflows/partsrelationshipservice-deploy.yml
> +      TF_VAR_image_registry: catenaxdev001acr.azurecr.io
For now ok but we should make these configurable

2021-09-17 12:05 UTC, algattik commented on .github/workflows/partsrelationshipservice-deploy.yml
> +      TF_VAR_image_registry: catenaxdev001acr.azurecr.io
https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#inputs

2021-09-17 12:07 UTC, ouphi commented on coreservices/partsrelationshipservice/terraform/variables.tf
> +  description = "PRS image tag that will be deployed."
I did it on purpose because having a default image does not help when deploying locally and makes the deployment experience worse IMO.
- If I add a default value tag that does not exist, the helm plan would work, but the helm deployment would fail as it would try to pull an image that does not exist.
- If I add a default value tag that exists, it will deploy this image, but I assume that if you make a local deployment, you want to try a specific image, or you want the latest image pushed.
Having a default value tag makes sense if the latest image is always tagged as "latest". But as it is not the case, I think it is better to ask the user the value. Then it is clear what is the image deployed.

2021-09-17 12:09 UTC, ouphi commented on coreservices/partsrelationshipservice/terraform/variables.tf
> +  description = "PRS image tag that will be deployed."
Another solution would be to also tag the latest image as latest and have latest as default tag. Any concerns?

2021-09-17 12:10 UTC, marcgs commented on .github/workflows/partsrelationshipservice-deploy.yml
> +          terraform init
If one of these commands fail, it will continue through the following ones, correct? If so, we should actually stop on an error.

2021-09-17 12:11 UTC, chrislomonico commented on coreservices/partsrelationshipservice/terraform/variables.tf
> +  description = "PRS image tag that will be deployed."
general good practice to avoid using `latest`

2021-09-17 12:12 UTC, marcgs commented on coreservices/partsrelationshipservice/Dockerfile
> +RUN find /build
@algattik What is this line for?

2021-09-17 12:13 UTC, marcgs commented on .github/workflows/partsrelationshipservice-deploy.yml
> +          terraform init
Perhaps the best is to extract a script in a similar way like for the dockerization?

2021-09-17 12:56 UTC, ouphi commented on .github/workflows/partsrelationshipservice-deploy.yml
> +          terraform init
I think exit on error is implicit in the `run`.
[I made a test](https://github.com/catenax/tractusx/runs/3632395784?check_suite_focus=true), I added `cd k`, it fails and next commands are not running.

2021-09-17 13:09 UTC, ouphi commented on coreservices/partsrelationshipservice/terraform/variables.tf
> +  description = "PRS image tag that will be deployed."
Then let's say no default tag value and force the user to provide one :)

2021-09-17 14:28 UTC, ouphi commented on .github/workflows/partsrelationshipservice-deploy.yml
> +      TF_VAR_image_registry: catenaxdev001acr.azurecr.io
Thank you for the insights. I will work on it in a different PR :).

2021-09-17 14:28 UTC, algattik commented on coreservices/partsrelationshipservice/Dockerfile
> +RUN find /build
oops, remove

2021-09-17 14:29 UTC, ouphi commented on coreservices/partsrelationshipservice/Dockerfile
> +RUN find /build
I removed it for now as it look like debugging.

2021-09-20 06:36 UTC, marcgs commented on coreservices/partsrelationshipservice/src/main/resources/application.yml
> -management:
Why did we remove he health probes?

2021-09-20 06:57 UTC, marcgs commented on coreservices/partsrelationshipservice/helm/prs/templates/deployment.yaml
> +              memory: 512Mi
liveness and readiness probes are missing :-)

2021-09-20 07:48 UTC, marcgs approved these changes

2021-09-20 07:51 UTC, algattik approved these changes

2021-09-20 07:51 UTC, merged