Feature/a1 mtdc@135 prometheus endpoint for jvm metrics
catenax/tractusx pull request #260
Opened 2021-11-15 14:13 UTC by cpeeyush

- Added https://github.com/prometheus/jmx_exporter as java agent.
- Added jar to repository so that we can run it locally as well.
- Kept yaml config to minimal for now until we have any specific ask to further refine it.

2021-11-15 14:15 UTC, cpeeyush commented on coreservices/partsrelationshipservice/Dockerfile
> +ENTRYPOINT ["java", "-javaagent:./applicationinsights-agent.jar", "-javaagent:./jmx_prometheus_javaagent-0.16.1.jar=4006:./jmx_prometheus_config.yml","-jar", "app.jar"]
I think it would be better if we take port number as a argument. I tried to make it work but so far its not successful. Can you please take a look ?
//CC @algattik @ouphi @marcgs

2021-11-15 15:20 UTC, cpeeyush commented on coreservices/partsrelationshipservice/Dockerfile
> +ENTRYPOINT ["java", "-javaagent:./applicationinsights-agent.jar", "-javaagent:./jmx_prometheus_javaagent-0.16.1.jar=4006:./jmx_prometheus_config.yml","-jar", "app.jar"]
or maybe not as we need to expose it on AKS as well. So having a fixed value necessary there.

2021-11-15 16:57 UTC, algattik requested changes
Let's not add jars to the repository :) Please add a download command to the Dockerfile like for the other agent

2021-11-15 16:58 UTC, algattik commented on coreservices/partsrelationshipservice/Dockerfile
> +ENTRYPOINT ["java", "-javaagent:./applicationinsights-agent.jar", "-javaagent:./jmx_prometheus_javaagent-0.16.1.jar=4006:./jmx_prometheus_config.yml","-jar", "app.jar"]
No need to make the port number an argument. In docker images typically port numbers are fixed and then mapped as needed

2021-11-15 16:59 UTC, algattik commented on coreservices/partsrelationshipservice/connector/jmx_prometheus_config.yml
> +startDelaySeconds: 0
we can move this file to ci/

2021-11-15 17:17 UTC, algattik commented
Would be good to also add the endpoints to `dev/prometheus/prometheus.yml` so we can visualise with docker-compose

2021-11-16 08:01 UTC, cpeeyush commented
> Let's not add jars to the repository :) Please add a download command to the Dockerfile like for the other agent
@algattik 
Sure, I will change it. Previously, I added this 3rd party jar so that even during local development devs can run it directly, similar to springboot where we have this endpoint available by actuator and can be used during local development.

2021-11-16 08:47 UTC, cpeeyush commented on coreservices/partsrelationshipservice/Dockerfile
> +ENTRYPOINT ["java", "-javaagent:./applicationinsights-agent.jar", "-javaagent:./jmx_prometheus_javaagent-0.16.1.jar=4006:./jmx_prometheus_config.yml","-jar", "app.jar"]
Yes, exactly so I am keeping it fixed. Thanks.

2021-11-16 08:48 UTC, cpeeyush commented on coreservices/partsrelationshipservice/connector/jmx_prometheus_config.yml
> +startDelaySeconds: 0
moved under cd/ following similar pattern what we did for application insight json.

2021-11-16 09:40 UTC, algattik commented
> Let's not add jars to the repository :) Please add a download command to the Dockerfile like for the other agent
> @algattik
> Sure, I will change it. Previously, I added this 3rd party jar so that even during local development devs can run it directly, similar to springboot where we have this endpoint available by actuator and can be used during local development.

I think docker is the way to go for that, otherwise you can provide a maven download artifact in README

2021-11-16 09:42 UTC, algattik commented on coreservices/partsrelationshipservice/Dockerfile
> +#Download jmx exporter agent
```suggestion
#Download jmx exporter agent (for non-spring boot applications)
```

2021-11-16 09:44 UTC, algattik approved these changes

2021-11-16 10:32 UTC, marcgs approved these changes

2021-11-16 10:33 UTC, marcgs commented
Run a small stress test with the multiple connector setup and monitored threads using this solution
<img width="1766" alt="Screenshot 2021-11-16 at 11 29 34" src="https://user-images.githubusercontent.com/5342234/141969407-3a4b0bea-c7c8-439f-b0e6-3bd0f496d9f7.png">

2021-11-16 10:48 UTC, ouphi approved these changes

2021-11-16 11:15 UTC, merged