Feature/a1 mtdc@ 161 Added connector keyvault and blob storage in terraform
catenax/tractusx pull request #271
Opened 2021-11-17 12:36 UTC by ouphi

2021-11-17 16:59 UTC, algattik requested changes

2021-11-17 16:59 UTC, algattik commented on coreservices/partsrelationshipservice/cd/terraform-connector-consumer/main.tf
> +  depends_on = [module.blob_storage]
Use the depends_on meta-argument to handle hidden resource or module dependencies that Terraform can't automatically infer.

Explicitly specifying a dependency is only necessary when a resource or module relies on some other resource's behavior but doesn't access any of that resource's data in its arguments.

2021-11-17 16:59 UTC, algattik commented on coreservices/partsrelationshipservice/cd/terraform-connector-consumer/main.tf
> +module "blob_storage" {
rename to connector_storage?

2021-11-17 16:59 UTC, algattik commented on coreservices/partsrelationshipservice/cd/terraform-connector-consumer/modules/blob_storage/main.tf
> +resource "azurerm_key_vault" "consumer-vault" {
comment would be nice (especially about what data will be stored there)

2021-11-17 16:59 UTC, algattik commented on coreservices/partsrelationshipservice/cd/terraform-connector-consumer/modules/blob_storage/main.tf
> +  account_replication_type = "GRS"
```suggestion
  account_replication_type = "LRS"
```

2021-11-17 16:59 UTC, algattik commented on coreservices/partsrelationshipservice/cd/terraform-connector-consumer/modules/blob_storage/main.tf
> +# Role assignment so that the primary identity may access the vault.
```suggestion
# Role assignment so that the PRS Consumer primary identity may access the vault.
```

2021-11-17 16:59 UTC, algattik commented on coreservices/partsrelationshipservice/cd/terraform-connector-consumer/modules/blob_storage/variables.tf
> +  description = "First or second part of name prefix used in naming resources. Use only lowercase letters and numbers."
why not use the prefix as in other tf modules? "First or second" is unclear

2021-11-17 16:59 UTC, algattik commented on coreservices/partsrelationshipservice/cd/terraform-connector-consumer/modules/blob_storage/variables.tf
> +variable "location" {
remove and use location inferred from resource group (as in other modules)

2021-11-17 16:59 UTC, algattik commented on coreservices/partsrelationshipservice/cd/terraform-connector-consumer/variables.tf
> +variable "environment" {
as above

2021-11-18 05:48 UTC, algattik requested changes

2021-11-18 05:48 UTC, algattik commented on coreservices/partsrelationshipservice/cd/terraform-connector-consumer/modules/connector_storage/main.tf
> +  name                = "cxmtpdc1-${var.environment}-prs-id"
```suggestion
  name                = "${var.prefix}-${var.environment}-prs-id"
```
as in other deployments

2021-11-18 05:48 UTC, algattik commented on coreservices/partsrelationshipservice/cd/terraform-connector-consumer/modules/connector_storage/main.tf
> +  name                        = "${var.environment}-consumer"
${var.prefix} in each resource

2021-11-18 05:48 UTC, algattik commented on coreservices/partsrelationshipservice/cd/terraform-connector-consumer/modules/connector_storage/main.tf
> +resource "azurerm_role_assignment" "current-user" {
```suggestion
resource "azurerm_role_assignment" "consumer-vault-current-user" {
```
to make it clearer when referring to this resource, what the assignment is to

2021-11-18 05:48 UTC, algattik commented on coreservices/partsrelationshipservice/cd/terraform-connector-consumer/modules/connector_storage/main.tf
> +# Primary key for the blob store.
```suggestion
# Store the Primary key for the connector Storage Account. This is required by the `azure.blob.provision` EDC extension
# to access the Storage Account.
```

2021-11-18 05:48 UTC, algattik commented on coreservices/partsrelationshipservice/cd/terraform-connector-consumer/modules/connector_storage/main.tf
> +resource "azurerm_storage_account" "connector-blobstore" {
```suggestion
# Storage Account used for exchanging data between the EDC Provider and EDC Consumer.
resource "azurerm_storage_account" "consumer-dataexchange" {
```

2021-11-18 05:48 UTC, algattik commented on coreservices/partsrelationshipservice/cd/terraform-connector-consumer/modules/connector_storage/main.tf
> +resource "azurerm_key_vault_secret" "blobstorekey" {
```suggestion
resource "azurerm_key_vault_secret" "consumer-dataexchange-account-key" {
```

2021-11-18 07:57 UTC, marcgs commented on coreservices/partsrelationshipservice/cd/terraform-connector-consumer/modules/connector_storage/main.tf
> +  name                        = "${var.environment}-consumer"
There are other resources unrelated to this PR that also don't use the prefix and environment to build up their name. Should we fix these too?
```
variable "application_insights_name" {
  type        = string
  description = "The Application Insights resource name."
  default     = "cxmtpdc1-dev-prs-appi"
}
```

2021-11-18 09:19 UTC, ouphi commented on coreservices/partsrelationshipservice/cd/terraform-connector-consumer/modules/connector_storage/main.tf
> +  name                        = "${var.environment}-consumer"
It is not possible to compose default var from other default var in terraform.
I could remove the application_insights_name var and use a local instead and compose its name from env and prefix var.
But I would do it in a different PR because if I remove this var it means I have to touch the pipeline as well and I would like to avoid to do that in this PR.
Or if you have another approach I am open.

2021-11-18 11:43 UTC, algattik commented on coreservices/partsrelationshipservice/cd/terraform-connector-consumer/modules/connector_storage/main.tf
> +  name                     = "${var.environment}consumer"
missing prefix

2021-11-18 11:43 UTC, algattik commented on coreservices/partsrelationshipservice/cd/terraform-connector-consumer/modules/connector_storage/variables.tf
> +variable "prefix" {
move up (before environment)

2021-11-18 11:44 UTC, algattik commented on coreservices/partsrelationshipservice/cd/terraform-connector-consumer/variables.tf
> +  description = "First part of name prefix used in naming resources. Use only lowercase letters and numbers."
move up (before environment)

2021-11-18 11:53 UTC, marcgs approved these changes

2021-11-18 12:31 UTC, marcgs commented on coreservices/partsrelationshipservice/cd/terraform-connector-consumer/main.tf
> +  prefix      = var.prefix
you need to pass `resource_group_name`here too

2021-11-18 12:34 UTC, algattik commented on coreservices/partsrelationshipservice/cd/terraform-connector-consumer/modules/connector_storage/variables.tf
> +  default     = "catenax-dev001-rg"
No need for defaults in module

2021-11-18 12:34 UTC, algattik approved these changes

2021-11-18 12:51 UTC, merged