Release of Semantic Hub Extension for PI1S4 System Demo https://jira.catena-x.net/browse/A1SLDT-20
catenax/tractusx pull request #290
Opened 2021-11-23 12:04 UTC by drcgjung

Successfully integrated and tested in dev042 see https://github.com/catenax/tractusx/pull/274

2021-11-23 16:29 UTC, JaneMcBrain commented on portal/code/tractus-x-portal/src/components/semantics/NewSemanticModel.tsx
> +      <TextField label="Publisher." value={publisher} onChange={onPublisherChange}/>
remove point

2021-11-23 16:39 UTC, JaneMcBrain requested changes

2021-11-23 16:39 UTC, JaneMcBrain commented on portal/code/tractus-x-portal/src/components/semantics/NewSemanticModel.tsx
> +      <TextField label="Publisher." value={publisher} onChange={onPublisherChange}/>
Remove point

2021-11-23 16:39 UTC, JaneMcBrain commented on portal/code/tractus-x-portal/src/components/semantics/NewSemanticModel.tsx
> +    console.log(option.key);
do we still need console.logs?

2021-11-23 16:39 UTC, JaneMcBrain commented on portal/code/tractus-x-portal/src/components/semantics/NewSemanticModel.tsx
> +  const buttonStyle2 = { width:200, marginLeft:10, marginRight: 10 };
margin:right is not needed

2021-11-23 16:39 UTC, JaneMcBrain commented on portal/code/tractus-x-portal/src/components/semantics/data.ts
> +  var method = 'POST';
I think you want to use this variable in line 68, otherwise it will be always POST

2021-11-23 17:06 UTC, drcgjung commented on portal/code/tractus-x-portal/src/components/semantics/data.ts
> +  var method = 'POST';
yes,, so i did not really test modify as you can see.

2021-11-26 08:06 UTC, JaneMcBrain approved these changes

2021-11-26 08:12 UTC, merged