Integration tests
catenax/tractusx pull request #33
Opened 2021-09-21 07:11 UTC by marcgs

2021-09-21 10:42 UTC, algattik commented on coreservices/partsrelationshipservice/prs-api/src/main/java/net/catenax/prs/controllers/PrsController.java
> -    @GetMapping(PrsApplication.API_PREFIX + "/vins/{vin}/partsTree")
ADR needs update

2021-09-21 14:47 UTC, marcgs commented on coreservices/partsrelationshipservice/prs-api/src/main/java/net/catenax/prs/controllers/PrsController.java
> -    @GetMapping(PrsApplication.API_PREFIX + "/vins/{vin}/partsTree")
Updated

2021-09-21 15:46 UTC, algattik requested changes
Repository layer logic is being leaked into the Service layer, leading to a less than ideal situation with UTs. Better to leave code clean and remove this filtering logic, even if it means all calls get the same canned response for now (disabling tests as needed)

2021-09-21 15:46 UTC, algattik commented on coreservices/partsrelationshipservice/integration-tests/src/test/java/net/catenax/prs/test/GetPartsTreeByObjectIdIntegrationTests.java
> +            .get("/api/v0.1/parts/{oneIDManufacturer}/{objectIDManufacturer}/partsTree")
extract constants with various strings? 
and/or extract method with a lot of these given()when() chains

2021-09-21 15:46 UTC, algattik commented on coreservices/partsrelationshipservice/integration-tests/src/test/java/net/catenax/prs/test/PrsIntegrationTestsBase.java
> +    public void setUpClass(){
linting

2021-09-21 15:46 UTC, algattik commented on coreservices/partsrelationshipservice/prs-api/src/main/java/net/catenax/prs/requests/PartsTreeByVinRequest.java
> +@SuppressWarnings({"PMD.CommentRequired", "PMD.CommentDefaultAccessModifier", "PMD.DefaultPackage"})
why these suppressions? (except CommentRequired)

2021-09-21 15:46 UTC, algattik commented on coreservices/partsrelationshipservice/prs-api/src/main/java/net/catenax/prs/services/PartsTreeQueryService.java
> +        final Optional<PartInfo> vehicle = partsTree.getPartInfos().stream()
ignoring this code in review, as assuming it's throwaway until the Repository comes in

2021-09-21 15:49 UTC, algattik commented on coreservices/partsrelationshipservice/integration-tests/src/test/java/net/catenax/prs/test/PrsIntegrationTestsBase.java
> +    public void setUpClass(){
```suggestion
    public void setUp() {
```
name is misleading

2021-09-21 15:51 UTC, algattik commented on coreservices/partsrelationshipservice/prs-api/src/main/java/net/catenax/prs/controllers/PrsController.java
> +     * Get a PartsTree for a part identified by a [oneId,objectId] tuple
nit: consider using SuppressWarnings so we could get rid of method javadoc on controllers

2021-09-21 15:51 UTC, marcgs commented on coreservices/partsrelationshipservice/prs-api/src/main/java/net/catenax/prs/services/PartsTreeQueryService.java
> +        final Optional<PartInfo> vehicle = partsTree.getPartInfos().stream()
Yes, this is just a temporary class, to be replaced by a proper service impl in https://jira.catena-x.net/browse/CATART0PO4-169

2021-09-21 15:55 UTC, marcgs commented on coreservices/partsrelationshipservice/integration-tests/src/test/java/net/catenax/prs/test/GetPartsTreeByObjectIdIntegrationTests.java
> +                .pathParam("oneIDManufacturer", "OID_CX_0001_ZFGRP")
These tests will base on a static data set loaded into our DB. We will need to adapt the ids once we get the final test data set, but it will use static ids, that we can define in a central place.

2021-09-21 15:56 UTC, marcgs commented on coreservices/partsrelationshipservice/prs-api/src/main/java/net/catenax/prs/requests/PartsTreeByVinRequest.java
> +@SuppressWarnings({"PMD.CommentRequired", "PMD.CommentDefaultAccessModifier", "PMD.DefaultPackage"})
To prevent issues with `@Value`, which generates `private final` automatically.

2021-09-21 15:57 UTC, marcgs commented on coreservices/partsrelationshipservice/prs-api/src/main/java/net/catenax/prs/services/PartsTreeQueryService.java
>   * Service for retrieving parts tree.
I understood the service will be defined in https://jira.catena-x.net/browse/CATART0PO4-169. In this PR I just focused in the REST API.

2021-09-22 07:14 UTC, ouphi approved these changes

2021-09-22 07:32 UTC, algattik approved these changes

2021-09-22 07:35 UTC, merged