CATX-A1-ODT-10 , Adding Login to Devops tooling's dashboard
catenax/tractusx pull request #345
Opened 2021-12-10 08:32 UTC by dhiraj-wakchaure

added router
added login page

2021-12-10 09:14 UTC, JaneMcBrain commented on devops-tooling/dashboard/src/App.tsx
> +  let auth = useAuth();
using const is the better approach, since this wont change

2021-12-10 09:14 UTC, JaneMcBrain commented on devops-tooling/dashboard/src/Auth/AuthContext.ts
> +let AuthContext = createContext<AuthContextType>(null!);
const

2021-12-10 09:14 UTC, JaneMcBrain commented on devops-tooling/dashboard/src/Auth/AuthProvider.tsx
> +    let [user, setUser] = useState<any>(null);
use const

2021-12-10 09:16 UTC, JaneMcBrain commented on devops-tooling/dashboard/src/components/Login/Login.tsx
> +  let navigate = useNavigate();
use const

2021-12-10 09:22 UTC, JaneMcBrain commented on devops-tooling/dashboard/src/components/Login/Login.tsx
> +            <TextField
is there a specific reason, why you used a Textfield instead of an Input?

2021-12-10 09:26 UTC, JaneMcBrain commented on devops-tooling/dashboard/src/components/Login/Login.tsx
> +            <TextField
Ok just saw, that the MUI docu is doing the same... ok fine

2021-12-10 09:57 UTC, dhiraj-wakchaure commented on devops-tooling/dashboard/src/App.tsx
> +  let auth = useAuth();
updated

2021-12-10 09:58 UTC, dhiraj-wakchaure commented on devops-tooling/dashboard/src/Auth/AuthContext.ts
> +let AuthContext = createContext<AuthContextType>(null!);
updated

2021-12-10 09:58 UTC, dhiraj-wakchaure commented on devops-tooling/dashboard/src/Auth/AuthProvider.tsx
> +    let [user, setUser] = useState<any>(null);
updated

2021-12-10 09:58 UTC, dhiraj-wakchaure commented on devops-tooling/dashboard/src/components/Login/Login.tsx
> +  let navigate = useNavigate();
updated

2021-12-13 08:35 UTC, JaneMcBrain requested changes

2021-12-13 08:35 UTC, JaneMcBrain commented on devops-tooling/dashboard/src/Auth/AuthProvider.tsx
> +    const signin = (newUser: string, callback: VoidFunction) => {
I would prefere signIn (CamelCase) here

2021-12-13 08:35 UTC, JaneMcBrain commented on devops-tooling/dashboard/src/Auth/AuthProvider.tsx
> +    const signout = (callback: VoidFunction) => {
CamelCase -> signOut

2021-12-13 08:35 UTC, JaneMcBrain commented on devops-tooling/dashboard/src/Auth/AuthService.ts
> +        return   localStorage.getItem('username') !== null;
remove spacing

2021-12-13 08:35 UTC, JaneMcBrain commented on devops-tooling/dashboard/src/Auth/RequireAuth.tsx
> +
remove spacing

2021-12-13 08:35 UTC, JaneMcBrain commented on devops-tooling/dashboard/src/components/Login/Login.tsx
> +            marginTop: 8,
I was also wondering why not using `mt: 8` here?

2021-12-13 08:35 UTC, JaneMcBrain commented on devops-tooling/dashboard/src/Auth/AuthContext.ts
> +
remove spacing

2021-12-13 08:53 UTC, dhiraj-wakchaure commented on devops-tooling/dashboard/src/components/Login/Login.tsx
> +            marginTop: 8,
ohh nice catch

2021-12-13 09:05 UTC, JaneMcBrain approved these changes

2021-12-13 09:07 UTC, merged