CATX-A1-ODT-135
catenax/tractusx pull request #363
Opened 2021-12-16 09:01 UTC by dhiraj-wakchaure

added sidebar layout

2021-12-16 11:36 UTC, JaneMcBrain requested changes

2021-12-16 11:36 UTC, JaneMcBrain commented on devops-tooling/dashboard/src/components/Layouts/AppLayout.tsx
> +export default function AppLayout() {
can we rename it to Layout? also the filename... ?

2021-12-16 11:36 UTC, JaneMcBrain commented on devops-tooling/dashboard/src/components/Layouts/AppLayout.tsx
> +          <Toolbar />
I would use margin instead - because it might look weird, that there is an empty Toolbox

2021-12-16 11:36 UTC, JaneMcBrain commented on devops-tooling/dashboard/src/components/Layouts/AppLayout.tsx
> +          <Toolbar />
here also use margin

2021-12-16 11:36 UTC, JaneMcBrain commented on devops-tooling/dashboard/src/components/Layouts/AppLayout.tsx
> +        <AppBar position="fixed" sx={{ zIndex: (theme) => theme.zIndex.drawer + 1 }}>
I would not use Toolbar inside the AppBar. Decide for one here?

2021-12-16 11:36 UTC, JaneMcBrain commented on devops-tooling/dashboard/src/components/Layouts/AppLayout.tsx
> +
spacing

2021-12-16 11:36 UTC, JaneMcBrain commented on devops-tooling/dashboard/src/components/Layouts/AppLayout.tsx
> +              Catena-X
indent or one line

2021-12-16 11:36 UTC, JaneMcBrain commented on devops-tooling/dashboard/src/components/Layouts/AppLayout.tsx
> +
remove spacing

2021-12-16 11:36 UTC, JaneMcBrain commented on devops-tooling/dashboard/src/components/Layouts/AppLayout.tsx
> +        <CssBaseline />
what is that for?

2021-12-16 11:36 UTC, JaneMcBrain commented on devops-tooling/dashboard/src/pages/Dashboard/Dashboard.tsx
>        <NetworkGraph nodes={nodesData} links={linksData}></NetworkGraph>
I would change the structure to the following: as Dashboard is a page component, the pages renders Layout and inside of Layout we have NetworkGraph. I think the logout functionality should be either stay here or having it inside of the Header-Component, but not in the Layout.

2021-12-16 11:36 UTC, JaneMcBrain commented on devops-tooling/dashboard/src/App.tsx
> +                <RequireAuth><Dashboard /></RequireAuth>
as Mentioned in the Dashboard.tsx I would rather have the layout inside of the Dashboard, since Dashboard is a page component...

2021-12-16 11:46 UTC, dhiraj-wakchaure commented on devops-tooling/dashboard/src/components/Layouts/AppLayout.tsx
> +export default function AppLayout() {
I gave AppLayout name , as it will be layout for our app , Layout will be too generic , in future we can have multiple layout

2021-12-16 11:46 UTC, dhiraj-wakchaure commented on devops-tooling/dashboard/src/components/Layouts/AppLayout.tsx
> +          <Toolbar />
is there any reason to use margin ?

2021-12-16 11:49 UTC, dhiraj-wakchaure commented on devops-tooling/dashboard/src/pages/Dashboard/Dashboard.tsx
>        <NetworkGraph nodes={nodesData} links={linksData}></NetworkGraph>
If multiple page have same layout then it will be redundant to use layout and parent everywhere , in case of change then we would need to change multiple spaces 
at route level it would be single point to change 

and Logout button is part of layout so we need to handle there only and needed we can create header component

2021-12-16 11:50 UTC, dhiraj-wakchaure commented on devops-tooling/dashboard/src/App.tsx
> +                <RequireAuth><Dashboard /></RequireAuth>
is there any reason for that ?

2021-12-16 11:53 UTC, dhiraj-wakchaure commented on devops-tooling/dashboard/src/components/Layouts/AppLayout.tsx
> +
I don't see any spacing related problem here , feel free to add lint rule if needed

2021-12-16 11:54 UTC, dhiraj-wakchaure commented on devops-tooling/dashboard/src/components/Layouts/AppLayout.tsx
> +
?

2021-12-16 11:58 UTC, dhiraj-wakchaure commented on devops-tooling/dashboard/src/components/Layouts/AppLayout.tsx
> +        <CssBaseline />
It reset the browser css style

2021-12-16 11:59 UTC, JaneMcBrain commented on devops-tooling/dashboard/src/components/Layouts/AppLayout.tsx
> +export default function AppLayout() {
well if we will have in the future several layouts, we can specify the name of a specific layout. If the component doesn't have any specification, we can keep it generic. Also for me it was confusing, that AppBar comes from MUI and AppLayout is from us.

2021-12-16 12:01 UTC, JaneMcBrain commented on devops-tooling/dashboard/src/components/Layouts/AppLayout.tsx
> +          <Toolbar />
When you remove Toolbar, which is not needed from the semantic point of view (only for upper spacing purpose, to not get overlaped by the header) you need to add some spacing here, otherwise the header overlaps it.

2021-12-16 12:05 UTC, dhiraj-wakchaure commented on devops-tooling/dashboard/src/components/Layouts/AppLayout.tsx
> +export default function AppLayout() {
I find it convenient, We can keep it now and change it later if needed

2021-12-16 12:07 UTC, JaneMcBrain commented on devops-tooling/dashboard/src/pages/Dashboard/Dashboard.tsx
>        <NetworkGraph nodes={nodesData} links={linksData}></NetworkGraph>
ah so you see the layout like a theme, that comes on top - ok that makes totally sense! :)

2021-12-16 12:15 UTC, JaneMcBrain commented on devops-tooling/dashboard/src/App.tsx
> +                <RequireAuth><Dashboard /></RequireAuth>
I saw it from the pages 'point of view': Routing defines the pages of each url and doesn't need to know which Layout is used. But you are right it is redundant, when always calling the layout inside of the Page component! I think your solution makes sense to me now!

2021-12-16 12:17 UTC, JaneMcBrain commented on devops-tooling/dashboard/src/components/Layouts/AppLayout.tsx
> +
I mean empty line here...

2021-12-16 12:32 UTC, dhiraj-wakchaure commented on devops-tooling/dashboard/src/components/Layouts/AppLayout.tsx
> +        <AppBar position="fixed" sx={{ zIndex: (theme) => theme.zIndex.drawer + 1 }}>
In mui it is recommended to use Appbar and toolbar together

2021-12-17 11:32 UTC, dhiraj-wakchaure commented on devops-tooling/dashboard/src/components/Layouts/AppLayout.tsx
> +          <Toolbar />
my main reason to use toolbar is to auto margin it without thinking how much margin need to apply and to which element. 

I have added margin for now have a look

2021-12-17 11:35 UTC, dhiraj-wakchaure commented on devops-tooling/dashboard/src/components/Layouts/AppLayout.tsx
> +          <Toolbar />
updated

2021-12-17 12:33 UTC, JaneMcBrain approved these changes

2021-12-17 12:34 UTC, merged