Feature/cax 12 devops@cplp 127 two keycloak instances
catenax/tractusx pull request #397
Opened 2022-01-26 09:22 UTC by raepple

- Automate deployment of two KeyCloak instances (aka "centralidp" and "sharedidp"
- Creation of new databases in PostgreSQL database service in terraform action
- Build and push of customized KeyCloak images to central ACR. Dockerfiles change the root context path in the base image to enable path-based routing of the two instances in K8S ingress rules

2022-01-26 12:34 UTC, evegufy commented on .github/workflows/iam.yml
> +                echo "::set-output name=workspace::dev003"
Whitespace sollten entfernt werden, oder du entfernt direkt die Zeilen 63-65, da es den Branch feature/CAX-9-onboarding nicht mehr gibt, weder in diesem Repo noch in unserem Fork.

2022-01-26 12:50 UTC, evegufy commented on .github/workflows/terraform.yml
> +              elif [[ "${{github.ref}}" == refs/heads/feature/CAX-12-devops@CPLP-127-two-keycloak-instances ]]; then
Remove CAX-12-devops@CPLP-127-two-keycloak-instances

2022-01-26 12:56 UTC, evegufy requested changes
Bei der Umgebungsermittlung sind mir 2 kleine Themen aufgefallen. Wäre klasse wenn du die iam file anpassen könntest. Die terraform file werde ich nach deinem Merge sowieso noch so anpassen, damit sie auch unserem Repo funktioniert, deshalb kann dort der feature/CAX-9-onboarding Branch auch erstmal noch drin bleiben, obwohl es ihn nicht mehr gibt.

2022-01-26 16:51 UTC, raepple commented on .github/workflows/iam.yml
> +                echo "::set-output name=workspace::dev003"
Removed deprecated branch from the workflow

2022-01-26 16:51 UTC, raepple commented on .github/workflows/terraform.yml
> +              elif [[ "${{github.ref}}" == refs/heads/feature/CAX-12-devops@CPLP-127-two-keycloak-instances ]]; then
Removed feature and deprecated team branches

2022-01-27 08:16 UTC, evegufy approved these changes

2022-01-27 08:17 UTC, merged