Split Semantic Services
catenax/tractusx pull request #471
Opened 2022-03-07 15:44 UTC by LuLeRoemer

This PR splits the Semantic Services code in the Semantic Hub and the Registry, which makes them independently deployable.

2022-03-11 11:23 UTC, fmisir commented
LGTM

2022-03-11 13:47 UTC, fmisir approved these changes

2022-03-15 12:41 UTC, drcgjung requested changes
Bug in kubernetes manifest versus workflow.

2022-03-15 12:41 UTC, drcgjung commented on infrastructure/manifests/semantics.yaml
> +        image: $CONTAINER_REGISTRY/semantic-hub/services${WORKSPACE}:$VERSION
I guess that is wrong. Should be "semantics/semantichub${WORKSPACE}:$VERSION"

2022-03-15 12:41 UTC, drcgjung commented on infrastructure/manifests/semantics.yaml
> +        image: $CONTAINER_REGISTRY/registry/services${WORKSPACE}:$VERSION
Same here semantics/registry${WORKSPACE}:$VERSION

2022-03-15 15:18 UTC, merged