Feature/cax 1 prs@183 Additional Integration Tests for Query API
catenax/tractusx pull request #73
Opened 2021-09-27 12:54 UTC by cpeeyush

- Additional Integration Tests for current Query API implementation.

2021-09-27 13:04 UTC, marcgs commented on coreservices/partsrelationshipservice/integration-tests/src/test/java/net/catenax/prs/test/GetPartsTreeByObjectIdIntegrationTests.java
> +                        .extract().asString();
We already checked the full response in previous tests, thus in this one I would just go with checking that the CE aspect is in the response using [jsonPath](https://github.com/json-path/JsonPath)

2021-09-27 13:48 UTC, cpeeyush commented on coreservices/partsrelationshipservice/integration-tests/src/test/java/net/catenax/prs/test/GetPartsTreeByObjectIdIntegrationTests.java
> +                        .extract().asString();
Updated. and removed the empty response file. Thanks

2021-09-27 14:23 UTC, marcgs commented on coreservices/partsrelationshipservice/integration-tests/src/test/java/net/catenax/prs/test/GetPartsTreeByObjectIdIntegrationTests.java
> +            .then()
rest assured supports:
```
.then()
.assertThat()
.statusCode(HttpStatus.OK.value())
.body("relationships", isEmpty())

```

2021-09-28 06:44 UTC, marcgs approved these changes

2021-09-28 06:44 UTC, marcgs commented
@cpeeyush I have added coverage for the AS_BUILT view as well (returning the same as AS_MAINTAINED)

2021-09-28 07:17 UTC, chrislomonico requested changes
see comments regarding the tests that imply an error response

2021-09-28 07:17 UTC, chrislomonico commented on coreservices/partsrelationshipservice/integration-tests/src/test/java/net/catenax/prs/test/GetPartsTreeByVinIntegrationTests.java
>          .then()
should this also assert for a bad request?

2021-09-28 07:17 UTC, chrislomonico commented on coreservices/partsrelationshipservice/integration-tests/src/test/java/net/catenax/prs/test/GetPartsTreeByVinIntegrationTests.java
>          .then()
should this as well be asserting the response? (applies to all where _returnsXXX is implied with the name

2021-09-28 07:41 UTC, cpeeyush commented on coreservices/partsrelationshipservice/integration-tests/src/test/java/net/catenax/prs/test/GetPartsTreeByVinIntegrationTests.java
>          .then()
Do you mean where we assert response body as well ? We have a follow up task for that to add an error response body and will also cover the assertion by updating our tests. Right now we only have response status codes from API.

2021-09-28 09:12 UTC, chrislomonico approved these changes

2021-09-28 09:13 UTC, merged