Feature/cax 1 idses@idsessent 19 env for gec
catenax/tractusx pull request #83
Opened 2021-09-29 07:32 UTC by Muravlev

## What's new

- Dev005 landscape is created.
- Connectors deployed in dev005 landscape

## Fix
- Fixed connector helm-chart ingress
- `azurerm_resource_group.shared_services_rg` in Terraform section is a data source now instead of resource. Thus, the import of this is no longer needed. @raepple could you please review the change?

2021-09-29 10:01 UTC, raepple approved these changes

2021-09-29 10:56 UTC, drcgjung requested changes
- The kubernetes version we use treats ingresses a bit different.
- The dev005 has been setup using an "old" terraform.yml which duplicated the environment names. Should be synced with main.
-

2021-09-29 10:56 UTC, drcgjung commented on connector/helm-chart/templates/ingress.yaml
> +    kubernetes.io/ingress.class: "nginx"
The non-beta version of ingresses (and the kubernetes version that is run in catenax) uses spec: ingressClassName: "xxx".
Furthermore we have yet setup two ingress classes "portal" and "service" in the terraform script. 
I guess that this ingress will not be correctly exposed/bound?
See https://github.com/catenax/tractusx/blob/feature/CAX-1-semantics%40CXMVP-50-semantic-adapter/infrastructure/manifests/semantics.yaml as an example.

2021-09-29 20:04 UTC, Muravlev commented on connector/helm-chart/templates/ingress.yaml
> +    kubernetes.io/ingress.class: "nginx"
I will update ingress in chart to work with relevant API version.
@raepple, could you explain what is the purpose of two ingress controllers? We have only one IP and thus only one domain name for whole landscape. Which ingress class should we use for connectors?
About ingresses - we definitely should came up with some convention (we still have only one domain name), but as far as I can see - there are no collisions. I haven't used `semantics` as the path prefix 😎
We can totally avoid collisions with another path prefix (`connectors` for example) for all connector instances, but then URI will be LARGE, e.g. https://catenaxintakssrv.germanywestcentral.cloudapp.azure.com/connectors/kaputt/consumer/

2021-09-29 21:02 UTC, Muravlev commented on connector/helm-chart/templates/ingress.yaml
> +    kubernetes.io/ingress.class: "nginx"
@drcgjung  Ingress is updated.  Please check changes

2021-09-30 10:48 UTC, drcgjung approved these changes

2021-09-30 13:00 UTC, merged